# Generated by Django 5.1.1 on 2024-10-04 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_articleview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='content',
        ),
    ]
