# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature/basecode

pool:
  name: terraform

resources:
- repo: self

variables:
  containerRegistry: 'newswebsite.azurecr.io'
  imageName: 'newswebsite'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build stage for django application
    jobs:
      - job: CheckingVariables
        displayName: CheckingVariables
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              
              echo '$(System.DefaultWorkingDirectory)'
              echo '$(Pipeline.Workspace)'
      - job: Build
        displayName: Build
        dependsOn:
          - CheckingVariables
        steps:
        - task: Docker@2
          inputs:
            command: 'buildAndPush'
            repository: '$(imageRepository)'
            Dockerfile: '$(DockerfilePath)'
            