apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsapp-deployment
  labels:
    app: news
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news
  template:
    metadata:
      labels:
        app: news
    spec:
      containers:
      - name: django
        image: ravitejadanda/newswebsite:v1
        ports:
        - containerPort: 8000
